rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecasofond
    username: postgres
    password: 1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true